Aareg
navikt/oppfolgingsplan-backend pull request #76
Opened 2024-09-06 09:46 UTC by MalazAlkoj

[Trello](https://trello.com/c/IokLx6VY/1250-migrere-aareg-til-ny-l%C3%B8sning-fra-knut-arild-sl%C3%A5tsve-p%C3%A5-slack-den-appen-tror-jeg-srvsyfooppfolgings-konsumerer-aareg-services-ved)
Det er et steg videre mot flytte/gjenskrive syfooppfolgingsplanservice til GCP.

2024-09-10 08:02 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/AaregClient.kt
> +    private val cleanedScope =
Burde vi være mer konsekvent med scope? Ser at mange teams har full scope-path i nais-filene, mulig vi burde det også? Alså å ha med api:// og .default

2024-09-10 08:02 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/AaregClient.kt
> +    private val cleanedScope =
..så slipper vi å legge det til i etterkant

2024-09-10 08:03 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/AaregClient.kt
> +        LOG.info("AaregClient with url: $url")
Kan kanskje fjerne log-statements

2024-09-10 08:03 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/AaregClient.kt
> +            LOG.info("Response from AAREG with request-url: $url")
Her også

2024-09-10 08:04 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/AaregClient.kt
> +        return "$url/api/v1/arbeidstaker/arbeidsforhold"
Kanskje bare inline dette som en string template i .exchange metoden

2024-09-11 06:50 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/AaregUtils.kt
> +object AaregUtils {
Kan eventuelt droppe object og bare ha funksjonen direkte tilgjengelig

2024-09-11 06:50 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/Ansettelsesperiode.kt
> +@Suppress("SerialVersionUIDInSerializableClass")
Tenker det er bedre å implementere serialversionuuid

2024-09-11 06:53 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/AntallTimerForTimeloennet.kt
> +@Suppress("SerialVersionUIDInSerializableClass")
Best å unngå supress

2024-09-11 06:53 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/Arbeidsavtale.kt
> +@Suppress("SerialVersionUIDInSerializableClass")
Best å unngå supress

2024-09-11 06:53 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/Arbeidsforhold.kt
> +@Suppress("SerialVersionUIDInSerializableClass")
Best å unngå supress

2024-09-11 06:54 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/Bruksperiode.kt
> +@Suppress("SerialVersionUIDInSerializableClass")
Best å unngå supress

2024-09-11 06:54 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/Gyldighetsperiode.kt
> +@Suppress("SerialVersionUIDInSerializableClass")
Best å unngå supress

2024-09-11 06:54 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/OpplysningspliktigArbeidsgiver.kt
> +@Suppress("SerialVersionUIDInSerializableClass")
Best å unngå supress

2024-09-11 06:54 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/Periode.kt
> +@Suppress("SerialVersionUIDInSerializableClass")
Best å unngå supress

2024-09-11 06:54 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/PermisjonPermittering.kt
> +@Suppress("SerialVersionUIDInSerializableClass")
Best å unngå supress

2024-09-11 06:54 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/Person.kt
> +@Suppress("SerialVersionUIDInSerializableClass")
Best å unngå supress

2024-09-11 06:54 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/Sporingsinformasjon.kt
> +@Suppress("SerialVersionUIDInSerializableClass")
Best å unngå supress

2024-09-11 06:54 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/Utenlandsopphold.kt
> +@Suppress("SerialVersionUIDInSerializableClass")
Best å unngå supress

2024-09-11 06:55 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdController.kt
> +        log.info("Henter stillinger for aktorId $aktorId, orgnummer $orgnummer")
Bør muligens unngå disse log-statementsa, kan være identifiserende info tror jeg

2024-09-11 06:56 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdController.kt
> +    private val log = LoggerFactory.getLogger(ArbeidsforholdController::class.java)
Kan bruke logger() fra Log.kt

2024-09-11 06:56 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdService.kt
> +    private val log = LoggerFactory.getLogger(javaClass)
Kan bruke logger() fra Log.kt

2024-09-11 06:57 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdService.kt
> +        log.info("Arbeidsforhold for arbeidstaker: $arbeidsforholdList")
Fjerne log

2024-09-11 10:10 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdService.kt
> +                    arbeidsforhold.arbeidsgiver!!.type.equals(OpplysningspliktigArbeidsgiver.Type.Organisasjon)
Vet vi at arbeidsgiver aldri er null her? Mtp dobbel utropstegn

2024-09-11 10:13 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdService.kt
> +                    arbeidsforhold.arbeidsavtaler!!
Vet vi at arbeidsavtaler ikke er null?

2024-09-11 10:13 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdService.kt
> +                        .sortedWith(compareBy<Arbeidsavtale, String?>(nullsLast()) { it.gyldighetsperiode!!.fom })
Samme med gyldighetsperiode

2024-09-11 10:14 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdService.kt
> +                                    it.gyldighetsperiode!!.fom,
Bør helst unngå å bruke doble utropstegn - dersom vi vet at DTO ikke er null burde kanskje DTO være non-nullable?

2024-09-16 09:12 UTC, MalazAlkoj commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdService.kt
> +                    arbeidsforhold.arbeidsavtaler!!
Jeg er ikke uenig, men blir det en del tull med return type osv når jeg fjerner `!!`. Da må vi legge til en del `emptyList...` osv.

2024-09-23 06:42 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdService.kt
> +                    arbeidsforhold.arbeidsavtaler!!
Dersom vi kun ønsker de som har arbeidsavtaler kan man kanskje filtrere først ut de som kun har arbeidsavtaler?

Ellers kan vi vel få en del nullpointerexception?

Hvorfor er egentlig arbeidsavtaler nullable i typen?

2024-09-23 06:43 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdService.kt
> +                                    arbeidsforhold.ansettelsesperiode!!.periode.fom
Samme med !! her og de andre stedene også

2024-09-23 06:44 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdService.kt
> +        /* Gyldighetsperiode sier noe om hvilken måned arbeidsavtalen er rapportert inn,
Bør kanskje legge kommentar over funksjon, så får man det med i autocomplete dokumentasjon

2024-09-23 09:24 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdController.kt
> +        val stillinger = arbeidsforholdService.arbeidstakersStillingerForOrgnummer(aktorId, date, orgnummer)
Jeg ser at denne tar inn persondata og orgnummer i requestparams.

Hvordan sikrer man at ingen misbruker dette? I andre apper slår man opp i syfobrukertilgang om man har tilgang - bør det være her også?

2024-09-23 09:24 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdController.kt
> +        @RequestHeader(NAV_PERSONIDENT_HEADER) aktorId: String,
Bør man ikke bruke fødselsnummer her? Aktørid er vel deprecated

2024-09-23 09:24 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdController.kt
> +    @GetMapping(produces = [APPLICATION_JSON_VALUE])
Bør dette være post-request siden den sender inn sensitive data?

2024-09-23 09:25 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdController.kt
> +        stillinger.forEach { log.info("Stilling: {${it.orgnummer}, ${it.fom}, ${it.tom}, ${it.yrke}, ${it.prosent}") }
Bør fjerne log-statement

2024-09-23 09:26 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdService.kt
> +    private fun arbeidsforholdList2StillingForOrgnummer(
Erstatte doble utropstegn i denne funksjonen

2024-09-23 09:27 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdService.kt
> +        val stillingsnavnFraFellesKodeverk =
Er det alltid den første som er riktig?

2024-09-23 09:28 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/felleskodeverk/Beskrivelse.kt
> +@Suppress("SerialVersionUIDInSerializableClass")
Kan implementere serialversionuuid

2024-09-23 09:28 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/felleskodeverk/Betydning.kt
> +@Suppress("SerialVersionUIDInSerializableClass")
Kan implementere serialversionuuid

2024-09-23 09:29 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/felleskodeverk/FellesKodeverkClient.kt
> +            LOG.info("We have received response from Felles Kodeverk: $response")
Bør kanskje fjerne log?

2024-09-23 09:29 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/narmesteleder/NarmesteLederClient.kt
> +        log.info("ExchangedToken: $exchangedToken")
Fjerne log-statements i denne funksjonen

2024-09-23 09:29 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/narmesteleder/NarmesteLederController.kt
> +        LOG.info("Henter stillinger from ArbeidsforholdService for $innloggetIdent")
Fjerne debug-logging

2024-09-23 09:30 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/pdl/PdlClient.kt
> +        val entity = createRequestEntity(PdlRequest(query ?: "", Variables(ident)))
Tom string bør ikke sendes inn i PdlRequest

2024-09-23 09:30 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/pdl/PdlClient.kt
> +            PdlRequest(query ?: "", Variables(ident = ident, grupper = gruppe))
Tom string bør ikke sendes inn

2024-09-23 09:31 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/pdl/PdlClient.kt
> +        val pdlIdenterReponse = pdlIdenter.body!!
Bør ikke ha doble utropstegn

2024-09-23 09:31 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/pdl/PdlClient.kt
> +                return pdlIdenterReponse.data?.hentIdenter?.identer?.first()?.ident!!
Samme her

2024-09-23 09:31 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/util/CredentialUtil.kt
> +fun basicCredentials(credentialUsername: String?, credentialPassword: String?): String {
Hvor blir denne brukt`?

2024-09-23 09:40 UTC, AudunSorheim commented on src/test/kotlin/no/nav/syfo/aareg/AaregClientTest.kt
> +    val isAaregServer = WireMockServer(9000)
Bra med wiremock!

2024-09-23 09:40 UTC, AudunSorheim commented on src/test/kotlin/no/nav/syfo/aareg/AaregClientTest.kt
> +    val restTemplate = mockk<RestTemplate>()
Resttemplate er ikke i bruk noe sted, det kan fjernes her fra både variabel og i testene.

2024-09-23 09:42 UTC, AudunSorheim commented on src/test/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdServiceTest.kt
> +        test_arbeidstakersStillingerForOrgnummer(arbeidsforholdList, aaregClient, pdlClient, arbeidsforholdService)
Foretrekker å ha kode inn i testene, slik at det blir enkelt å lese hva som er mocket, og hva som blir assertet.

Blir usikker på hva som skjer når jeg leser "test_arbeidstakersStillingerForOrgnummer"

2024-09-23 09:43 UTC, AudunSorheim commented on src/test/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdServiceTest.kt
> +                                tom = stilling2StopDate.toStr()
toStr() ser ut til å være en intern metode. Bør det være toString?

2024-09-23 09:45 UTC, AudunSorheim commented on src/test/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdServiceTest.kt
> +import org.assertj.core.api.Assertions.assertThat
AssertJ er bra, men for å ha konsistens bør vi holde oss til 1 assertion framework. Det kommer innebygget i kotest - https://kotest.io/docs/assertions/assertions.html

2024-09-23 09:45 UTC, AudunSorheim commented on src/test/kotlin/no/nav/syfo/aareg/AaregClientTest.kt
> +import org.assertj.core.api.Assertions.assertThat
Her også, gjerne erstatte assertj med kotest

2024-09-23 09:47 UTC, AudunSorheim requested changes
Lagt inn noen kommentarer/innspill :)

2024-09-23 11:10 UTC, MalazAlkoj commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdController.kt
> +        val stillinger = arbeidsforholdService.arbeidstakersStillingerForOrgnummer(aktorId, date, orgnummer)
Det er veldig godt poeng, den er ikke i bruk ennå. 
Men det er ikke dumt å ha tilgangskontroll sjekk, også før vi tar den i bruk.

2024-09-23 11:36 UTC, Vitenok requested changes

2024-09-23 11:36 UTC, Vitenok commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdController.kt
> +        @RequestHeader(NAV_PERSONIDENT_HEADER) aktorId: String,
Enig

2024-09-23 14:21 UTC, MalazAlkoj commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdService.kt
> +        val stillingsnavnFraFellesKodeverk =
Godt spørsmål, jeg fikk inntrykk at det er i praksis 1 to 1 og det er svaret på en måte. Men kanskje jeg tok feil 🤔

2024-09-24 11:14 UTC, MalazAlkoj commented on src/main/kotlin/no/nav/syfo/pdl/PdlClient.kt
> +        val entity = createRequestEntity(PdlRequest(query ?: "", Variables(ident)))
Throws IOException foreløpig, men liker godt forslaget og vi kan vurdere å forbedre koden etter hvert.

2024-09-27 07:33 UTC, AudunSorheim commented on src/main/kotlin/no/nav/syfo/aareg/service/ArbeidsforholdController.kt
> +                log.info("Hentet ${stillinger.size} stillinger")
Kan nok fjerne infolog

2024-09-27 07:36 UTC, AudunSorheim approved these changes

2024-09-27 09:19 UTC, Vitenok approved these changes

2024-09-27 09:20 UTC, merged